### PR TITLE
feat(ext): pdo_oci, pdo_sqlsrv, sqlsrv extension

### PR DESCRIPTION
**Pull request by bgastaldi**
Add extension for Oracle and SQLServer

### CODE REVIEW

**Comment by leocavalcante** [comment]
May I ask you: it is a lot of code into the`Dockerfile` to build a image.  Do you think it worth the effort for such extensions that are not so much used between the PHP community?

Remember that people can always have a `Dockerfile` with a `FROM opencode/phpctl` and a `.phpctlrc` with a `PHPCTL_IMAGE` to use the same `phpctl` commands, but with a custom, more specialized image.

**Comment by bgastaldi** [comment]
> May I ask you: it is a lot of code into the`Dockerfile` to build a image. Do you think it worth the effort for such extensions that are not so much used between the PHP community?
> 
> Remember that people can always have a `Dockerfile` with a `FROM opencode/phpctl` and a `.phpctlrc` with a `PHPCTL_IMAGE` to use the same `phpctl` commands, but with a custom, more specialized image.

Yes, I agree with you regarding Oracle. As for SQL Server, its usage is more widespread. However, the focus here was to have the availability of resources, and some people may not use it because the project doesn't support it.

I understand your perspective on using PHPCTL_IMAGE, but the main issue is the knowledge required to use it or build it correctly.

What do you think about creating an "incubator"? We could keep these Dockerfiles there. I believe it would be a way to contribute.

**Comment by leocavalcante** [comment]
> Edit: New dicussion? rs

Sure! Would be nice to hear about from more people. Maybe it isn't less used as I think

**Comment by bgastaldi** [comment]
> > Edit: New dicussion? rs
> 
> Sure! Would be nice to hear about from more people. Maybe it isn't less used as I think

Done!

**Pull request closed without merging**
